{{- if and .Values.canaryTokenUrl (not .Values.canaryExistingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "krawl.fullname" . }}-canary
  labels:
    {{- include "krawl.labels" . | nindent 4 }}
type: Opaque
stringData:
  canary-token-url: {{ .Values.canaryTokenUrl | quote }}
{{- end }}
