{{- if and (or .Values.cloudflare.accountId .Values.cloudflare.authToken) (not .Values.cloudflare.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "krawl.fullname" . }}-cloudflare
  labels:
    {{- include "krawl.labels" . | nindent 4 }}
type: Opaque
stringData:
  cloudflare-account-id: {{ .Values.cloudflare.accountId | quote }}
  cloudflare-auth-token: {{ .Values.cloudflare.authToken | quote }}
{{- end }}
