{{- if and .Values.config.map.api_key (not .Values.mapExistingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "krawl.fullname" . }}-map
  labels:
    {{- include "krawl.labels" . | nindent 4 }}
type: Opaque
stringData:
  map-api-key: {{ .Values.config.map.api_key | quote }}
{{- end }}
